import csv
import os
import random

BASE_DIR = r"d:\aptitude preparation plaform\question_bank\debugging_and_code_logic"
CSV_PATH = os.path.join(BASE_DIR, "debugging_and_code_logic.csv")

questions = []

def add_q(text, a, b, c, d, ans):
    text = text.replace(";", ",")
    questions.append(f"{text};{a};{b};{c};{d};{ans},,,,,,,,")

def shuffle_and_add(text, correct, dummy1, dummy2, dummy3):
    opts = [correct, dummy1, dummy2, dummy3]
    random.shuffle(opts)
    ans_idx = opts.index(correct)
    ans_char = chr(65 + ans_idx)
    add_q(text, opts[0], opts[1], opts[2], opts[3], ans_char)

print("Generating Python-specific Debugging & Code Logic variations...")

# 1. Mutable Default Arguments (Python Trap)
for _ in range(50):
    val = random.randint(1, 10)
    code = f"def add_item(num, lst=[]):\n  lst.append(num)\n  return lst\n\nadd_item(1)\nprint(add_item({val}))"
    ans = f"[1, {val}]"
    d1 = f"[{val}]"
    d2 = f"[1]"
    d3 = f"[[1], [{val}]]"
    
    q_txt = f"What is printed by this Python snippet demonstrating mutable defaults?<br><code>{code}</code>"
    shuffle_and_add(q_txt, ans, d1, d2, d3)

# 2. Late Binding Closures / Lambda scopes
for _ in range(50):
    outer_loop = random.randint(3, 5)
    call_idx = random.randint(0, outer_loop - 1)
    
    code = f"funcs = [lambda: i for i in range({outer_loop})]\nprint(funcs[{call_idx}]())"
    # Because of late binding, 'i' evaluates to its final value during loop completion
    ans = str(outer_loop - 1)
    
    d1 = str(call_idx)
    d2 = f"[{call_idx}]"
    d3 = "IndexError"
    
    q_txt = f"Trace the closure output in this Python code:<br><code>{code}</code>"
    shuffle_and_add(q_txt, ans, d1, d2, d3)

# 3. is vs == (Identity vs Equality)
for _ in range(50):
    code = f"a = [1, 2, 3]\nb = a[:]\nprint(a == b, a is b)"
    ans = "True False"
    d1 = "True True"
    d2 = "False False"
    d3 = "False True"
    
    q_txt = f"What is the output regarding Python object identity?<br><code>{code}</code>"
    shuffle_and_add(q_txt, ans, d1, d2, d3)

# 4. Exception blocks (Else/Finally Execution trace)
for _ in range(50):
    err_var = random.choice([True, False])
    code = f"def trace():\n  try:\n    if {str(err_var)}:\n      raise ValueError()\n    print('A')\n  except ValueError:\n    print('B')\n  else:\n    print('C')\n  finally:\n    print('D')\ntrace()"
    
    if err_var:
        ans = "B D"
    else:
        ans = "A C D"
        
    opts = ["A B C D", "A C D", "B D", "B C D", "A D"]
    if ans in opts: opts.remove(ans)
    
    q_txt = f"Trace the print statements generated by this Python exception flow:<br><code>{code}</code>"
    shuffle_and_add(q_txt, ans, opts[0], opts[1], opts[2])

# 5. Modifying list while iterating (Python)
for _ in range(50):
    find_val = random.randint(2, 4)
    code = f"lst = [1, {find_val}, 3, 4]\nfor item in lst:\n  if item == {find_val}:\n    lst.remove(item)\nprint(lst)"
    # If find_val is 2 at index 1: list becomes [1, 3, 4]. loop moves to index 2 (val 4). item 3 is skipped.
    # It prints [1, 3, 4]. Removing while iterating skips the next item.
    
    ans = f"It skips checking the element immediately succeeding {find_val} and outputs a modified list."
    d1 = "RuntimeError: dictionary changed size during iteration"
    d2 = "ConcurrentModificationException"
    d3 = "It throws an IndexError."
    
    q_txt = f"What is the primary logical flaw and result of this Python loop?<br><code>{code}</code>"
    shuffle_and_add(q_txt, ans, d1, d2, d3)

# 6. Global scope shadowing
for _ in range(50):
    glob_val = random.randint(10, 20)
    loc_val = random.randint(30, 40)
    
    code = f"x = {glob_val}\ndef func():\n  x = {loc_val}\n  def inner():\n    nonlocal x\n    x += 5\n  inner()\nfunc()\nprint(x)"
    # The printed x is the global one, which hasn't changed.
    ans = str(glob_val)
    d1 = str(loc_val)
    d2 = str(loc_val + 5)
    d3 = str(glob_val + 5)
    
    q_txt = f"Trace the final value of 'x' printed:<br><code>{code}</code>"
    shuffle_and_add(q_txt, ans, d1, d2, d3)

print(f"Adding {len(questions)} Python debugging variations to CSV...")

with open(CSV_PATH, 'a', newline='', encoding='utf-8') as f:
    for q in questions:
        f.write(q + "\n")

print("Done generating Python distinct debugging logic questions.")
