# Generated by Django 6.0.1 on 2026-01-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_alter_storeitem_id_alter_useritem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
