# Generated by Django 6.0.1 on 2026-02-22 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_alter_storeitem_id_alter_useritem_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='MonthlySpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spin_date', models.DateTimeField(auto_now_add=True)),
                ('reward_type', models.CharField(choices=[('COINS', 'Coins'), ('LIVES', 'Lives'), ('FRAME', 'Golden Frame')], max_length=10)),
                ('reward_value', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_spins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-spin_date'],
            },
        ),
    ]
