# Generated by Django 6.0.1 on 2026-02-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0007_alter_storeitem_id_alter_useritem_id'),
        ('gamification', '0007_alter_storeitem_id_alter_useritem_id_monthlyspin'),
    ]

    operations = [
    ]
