# Generated by Django 6.0.1 on 2026-02-25 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0008_alter_monthlyspin_id_alter_storeitem_id_and_more'),
        ('gamification', '0008_merge_20260224_2025'),
    ]

    operations = [
    ]
