# Generated by Django 6.0.1 on 2026-01-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interested_field',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
