# Generated by Django 6.0.1 on 2026-01-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_current_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='interested_field',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
