# Generated by Django 6.0.1 on 2026-02-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.CharField(blank=True, help_text='Company Name, College, etc.', max_length=255),
        ),
    ]
