# Generated by Django 5.2.4 on 2026-02-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_certificate_id_alter_conversation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='github_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
