# Generated by Django 6.0.1 on 2026-02-25 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_certificate_id_alter_conversation_id_and_more'),
        ('users', '0014_sitesetting_alter_certificate_id_and_more'),
    ]

    operations = [
    ]
