# Generated by Django 6.0.1 on 2026-03-18 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_20260225_0837'),
        ('users', '0015_merge_20260225_0850'),
    ]

    operations = [
    ]
