# Generated by Django 6.0.1 on 2026-06-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0001_initial'),
        ('tests', '0008_question_question_type_question_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='matches', to='tests.question'),
        ),
    ]
