# Generated by Django 6.0.1 on 2026-03-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_alter_category_id_alter_option_id_alter_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('LOGICAL', 'Logical Reasoning'), ('CODING', 'Coding/Programming')], default='MCQ', max_length=15),
        ),
        migrations.AddField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(default=60, help_text='Time limit for this question in seconds'),
        ),
    ]
